### PR TITLE
I'm a cool PR

### PR DESCRIPTION
**Pull request by janeon**
So cool

### CODE REVIEW

**Comment by jhsieh2** [comment]
Hey fat guy, fix your code!

**Comment by janeon** [comment]
> Watch your language.
> Friendly discussion only 🤔

Hey I'm not sure what you mean? Just being a buddy here

**Comment by ai-xiaihai** [comment]
> > Watch your language.
> > Friendly discussion only 🤔
> 
> Hey I'm not sure what you mean? Just being a buddy here

Fat shaming is bad. You should not fat shame fellow contributors. All bodies are beautiful. 🥰 
Your comment looks like fat-shaming to me 👎

**Comment by jhsieh2** [comment]
Okay I understand now, sorry! Reworded it

**Comment by ai-xiaihai** [comment]
thank you bye

**Pull request closed without merging**
